name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      safe_name: ${{ steps.artifact.outputs.safe_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Cache Gradle files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleRelease --no-daemon --stacktrace

      - name: List APK files
        run: |
          echo "APK files built:"
          find app/build/outputs/apk/release -name "*.apk" -type f

      - name: Rename APK
        run: |
          mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/chat.apk

      - name: Sanitize artifact name
        id: artifact
        run: |
          SAFE_NAME="chat-release-apk-${GITHUB_REF_NAME//\//_}"
          echo "safe_name=$SAFE_NAME" >> $GITHUB_OUTPUT

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact.outputs.safe_name }}
          path: app/build/outputs/apk/release/*.apk
          retention-days: 30
          if-no-files-found: error
